### ISSUE TITLE
Code enhance/ Fix code structures to be easy to maintain

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/Ainory#35]
# Todo
- [x] Separate urls to each app
- [x] Separate serializer to each model
- [x] Separate UserSerializer for list and detail
- [x] Separate EventSerializer for list and detail
- [x] Separate MemorySerializer for list and detail

# Checklist 
- [x] Tests
- [x] Flake8
