### ISSUE TITLE
Add File system to users

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/ainory#38]
# Todo 
- [x] Add Picture model to users app
- user/event(null=True)/file(FileField)/
- [x] Add Create/Destroy system 
- [x] Fix UserDetailSerializer to include pictures

# Checklist
- [x] Tests
- [x] Flake8
