### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/ainory#40]
# Todo 
- [x] setup notifications app
- [x] Create Inbox model 
- [x] Add Inbox List system
- [x] Add Inbox Destroy system

# Checklist
- [x] Tests
- [x] Flake8
