### ISSUE TITLE
Fix Serializers

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/ainory#43]
# Todo
- [x] Fix users serializer
- [x] Fix event serializer
- [x] Fix memory seliaizer
- Add List 

# Checklist
- [x] Tests
- [x] Flake8
