### ISSUE TITLE
Setup Vue.js project called frontend

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/ainory#50]
# Todo
- [ ] Create frontend project
- [ ] Setup docker for vue.js
- [ ] Setup dependencies (axios, webpack-bundle-tracker)

# Checklist
- [ ] Tests
- [ ] Flake8
